import axios from "axios"
import { getHeaders } from "../auth/authService"
const BASE = "http://localhost:8000"
export const login = (d) => axios.post(`${BASE}/login`, d)
export const changePassword = (d) => axios.post(`${BASE}/changePassword`, d)
export const getProfile = () => axios.get(`${BASE}/user/profile`, { headers: getHeaders() })
export const updateProfile = (d) => axios.post(`${BASE}/user/updateProfile`, d, { headers: getHeaders() })
export const getDashboardStats = () => axios.get(`${BASE}/admin/dashboardStats`, { headers: getHeaders() })
export const getUsers = () => axios.get(`${BASE}/admin/users`, { headers: getHeaders() })
export const updateUserStatus = (d) => axios.post(`${BASE}/admin/updateUserStatus`, d, { headers: getHeaders() })
export const getAdminGames = () => axios.get(`${BASE}/admin/games`, { headers: getHeaders() })
export const addGame = (d) => axios.post(`${BASE}/admin/addGame`, d, { headers: getHeaders() })
export const updateGame = (d) => axios.post(`${BASE}/admin/updateGame`, d, { headers: getHeaders() })
export const deleteGame = (id) => axios.get(`${BASE}/admin/deleteGame/${id}`, { headers: getHeaders() })
export const getAdminSlots = () => axios.get(`${BASE}/admin/slots`, { headers: getHeaders() })
export const addSlot = (d) => axios.post(`${BASE}/admin/addSlot`, d, { headers: getHeaders() })
export const updateSlot = (d) => axios.post(`${BASE}/admin/updateSlot`, d, { headers: getHeaders() })
export const deleteSlot = (id) => axios.get(`${BASE}/admin/deleteSlot/${id}`, { headers: getHeaders() })
export const getAdminSeats = () => axios.get(`${BASE}/admin/seats`, { headers: getHeaders() })
export const addSeat = (d) => axios.post(`${BASE}/admin/addSeat`, d, { headers: getHeaders() })
export const updateSeat = (d) => axios.post(`${BASE}/admin/updateSeat`, d, { headers: getHeaders() })
export const deleteSeat = (id) => axios.get(`${BASE}/admin/deleteSeat/${id}`, { headers: getHeaders() })
export const getBookings = () => axios.get(`${BASE}/admin/bookings`, { headers: getHeaders() })
export const updateBooking = (d) => axios.post(`${BASE}/admin/updateBooking`, d, { headers: getHeaders() })
export const getPayments = () => axios.get(`${BASE}/admin/payments`, { headers: getHeaders() })
export const getFeedbacks = () => axios.get(`${BASE}/admin/feedbacks`, { headers: getHeaders() })
